### ISSUE TITLE
Status on level of completion for MCP Program + docs

### ISSUE THREAD

**Issue by MegaPanchamZ** [Vchandrapati/ENG3000MCP#1]
Hey, MCP Team, I'm just checking to see how you're doing regarding the MCP program design and implementation.

I notice that there have been few commits from anyone in the last 2 weeks. Does this mean the program is completed, or has this repo become an artifact?

Please let me know if you have any docs prepared on how you configure the environment (if there are any specifics, or compiled *.jar programs) 

Thanks,
Deb

**Comment by Vchandrapati** [comment]
The basis of the project has been completed, any further update progress has been slowed down for the time being in favour of completing other assignments and documentation. The project timeline is not set to move along until at least  week 6 so any progress may be slower until that point.

In terms of preparing the environment that is something we are not planning on providing documentation for. How the program is compiled and exported is something that is left up to the individual CCP groups and any question should be directed to Rex and the teaching staff.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Deb Kumar ***@***.***>
Sent: Monday, August 19, 2024 5:56:26 PM
To: Vchandrapati/ENG3000MCP ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Vchandrapati/ENG3000MCP] Status on level of completion for MCP Program + docs (Issue #1)


Hey, MCP Team, I'm just checking to see how you're doing regarding the MCP program design and implementation.

I notice that there have been few commits from anyone in the last 2 weeks. Does this mean the program is completed, or has this repo become an artifact?

Please let me know if you have any docs prepared on how you configure the environment (if there are any specifics, or compiled *.jar programs)

Thanks,
Deb
